<template>
  <div class="max-w-4xl mx-auto p-8 bg-white rounded-xl shadow-lg">
    <h1 class="text-3xl font-extrabold mb-6 text-gray-900">
      {{ isEdit ? 'Edit Invoice' : 'Create Invoice' }}
    </h1>

    <form @submit.prevent="handleSubmit" class="space-y-8">
      <!-- Invoice Meta -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-1" for="invoice-number">Invoice Number</label>
          <input
            id="invoice-number"
            v-model="form.invoice_number"
            type="text"
            class="input"
            readonly
            placeholder="Auto-generated by system"
          />
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-1" for="invoice-date">Invoice Date</label>
          <input
            id="invoice-date"
            v-model="form.invoice_date"
            type="date"
            class="input"
            required
          />
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-1" for="due-date">Due Date</label>
          <input
            id="due-date"
            v-model="form.due_date"
            type="date"
            class="input"
            required
          />
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-1" for="customer">Customer</label>
          <select
            id="customer"
            v-model="form.customer_id"
            class="input"
            required
          >
            <option value="" disabled>Select Customer</option>
            <option v-for="customer in customers" :key="customer.id" :value="customer.id">
              {{ customer.name }}
            </option>
          </select>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-1" for="status">Status</label>
          <select
            id="status"
            v-model="form.status"
            class="input"
            required
          >
            <option value="unpaid">Unpaid</option>
            <option value="paid">Paid</option>
            <option value="overdue">Overdue</option>
          </select>
        </div>

        <div class="md:col-span-2">
          <label class="block text-sm font-semibold text-gray-700 mb-1" for="notes">Notes</label>
          <textarea
            id="notes"
            v-model="form.notes"
            class="input resize-y"
            rows="3"
            placeholder="Additional notes or terms"
          ></textarea>
        </div>
      </div>

      <!-- Invoice Items -->
      <div>
        <h2 class="text-xl font-semibold mb-4 text-gray-800">Invoice Items</h2>
        <div
          v-for="(item, index) in form.items"
          :key="index"
          class="grid grid-cols-1 sm:grid-cols-12 gap-3 items-end mb-3"
        >
          <div class="sm:col-span-6">
            <label class="block text-xs font-semibold text-gray-600 mb-1" :for="'desc-' + index">Description</label>
            <input
              :id="'desc-' + index"
              v-model="item.description"
              placeholder="Description"
              class="input"
              required
            />
          </div>
          <div class="sm:col-span-2">
            <label class="block text-xs font-semibold text-gray-600 mb-1" :for="'qty-' + index">Quantity</label>
            <input
              :id="'qty-' + index"
              v-model.number="item.quantity"
              type="number"
              min="1"
              class="input"
              placeholder="Qty"
              required
            />
          </div>
          <div class="sm:col-span-3">
            <label class="block text-xs font-semibold text-gray-600 mb-1" :for="'price-' + index">Unit Price</label>
            <input
              :id="'price-' + index"
              v-model.number="item.unit_price"
              type="number"
              min="0"
              step="0.01"
              class="input"
              placeholder="Unit Price"
              required
            />
          </div>
          <div class="sm:col-span-1 text-right">
            <button
              type="button"
              @click="removeItem(index)"
              class="btn btn-danger"
              :aria-label="`Remove item ${index + 1}`"
              title="Remove Item"
            >
              &times;
            </button>
          </div>
        </div>

        <button
          type="button"
          @click="addItem"
          class="btn btn-secondary mt-2"
        >
          + Add Item
        </button>
      </div>

      <!-- Total -->
      <div class="text-right font-extrabold text-2xl text-gray-900 mt-8">
        Total: ${{ invoiceTotal.toFixed(2) }}
      </div>

      <!-- Submit -->
      <div class="mt-8 flex justify-end">
        <button
          type="submit"
          class="btn btn-primary px-10 py-3 text-lg"
        >
          {{ isEdit ? 'Update Invoice' : 'Create Invoice' }}
        </button>
      </div>
    </form>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import axios from '@/axios';

const route = useRoute();
const router = useRouter();

const isEdit = ref(false);
const customers = ref([]);

const form = ref({
  invoice_number: '',
  invoice_date: '',
  due_date: '',
  customer_id: '',
  status: 'unpaid',
  notes: '',
  items: [
    { description: '', quantity: 1, unit_price: 0 }
  ]
});

const resetForm = () => {
  form.value = {
    invoice_number: '',
    invoice_date: '',
    due_date: '',
    customer_id: '',
    status: 'unpaid',
    notes: '',
    items: [
      { description: '', quantity: 1, unit_price: 0 }
    ]
  };
};

const fetchCustomers = async () => {
  try {
    const res = await axios.get('/customers');
    customers.value = res.data.data;
  } catch (error) {
    console.error('Failed to fetch customers:', error);
  }
};

const fetchInvoice = async () => {
  const { id } = route.params;
  if (id) {
    try {
      const res = await axios.get(`/invoices/${id}`);
      const invoice = res.data.invoice;
      form.value = {
        invoice_number: invoice.invoice_number,
        invoice_date: invoice.invoice_date,
        due_date: invoice.due_date,
        customer_id: invoice.customer_id,
        status: invoice.status,
        notes: invoice.notes,
        items: invoice.items.length > 0
          ? invoice.items
          : [{ description: '', quantity: 1, unit_price: 0 }],
      };
    } catch (error) {
      console.error('Failed to fetch invoice:', error);
    }
  }
};

const handleSubmit = async () => {
  try {
    if (isEdit.value) {
      await axios.put(`/invoices/${route.params.id}`, form.value);
    } else {
      const res = await axios.post('/invoices', form.value);
      form.value.invoice_number = res.data.data.invoice_number || '';
      isEdit.value = true;
    }
    router.push('/invoices');
  } catch (error) {
    console.error('Failed to submit invoice:', error);
  }
};

const addItem = () => {
  form.value.items.push({ description: '', quantity: 1, unit_price: 0 });
};

const removeItem = (index) => {
  if (form.value.items.length > 1) {
    form.value.items.splice(index, 1);
  }
};

const invoiceTotal = computed(() =>
  form.value.items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0)
);

watch(
  () => route.params.id,
  async (newId) => {
    if (newId) {
      isEdit.value = true;
      await fetchInvoice();
    } else {
      isEdit.value = false;
      resetForm();
    }
  },
  { immediate: true }
);

onMounted(() => {
  fetchCustomers();
});
</script>
<style scoped>
/* Container */
.max-w-4xl {
  max-width: 800px;        /* Limit container width */
  margin-left: auto;
  margin-right: auto;
  background: linear-gradient(135deg, #f0f5ff 0%, #e0f7fa 100%);
  box-shadow: 0 10px 25px rgba(0, 90, 140, 0.15);
  border-radius: 1rem;
  padding: 2.5rem;
  font-family: 'Inter', sans-serif;
}

/* Headings */
h1, h2 {
  font-family: 'Poppins', sans-serif;
  color: #1e293b; /* dark slate */
  text-shadow: 0 1px 2px rgba(0,0,0,0.1);
}

h1 {
  font-weight: 700;
  font-size: 2.5rem;
  margin-bottom: 1.5rem;
}

h2 {
  font-weight: 600;
  font-size: 1.5rem;
  margin-bottom: 1rem;
}

/* Inputs and Select */
.input {
  width: 100%;
  max-width: 350px;           /* Limit input width */
  background-color: #fff;
  border: 2px solid transparent;
  border-radius: 0.75rem;
  padding: 0.625rem 1rem;
  font-size: 1rem;
  color: #334155;
  box-shadow: 0 1px 5px rgba(50, 115, 220, 0.1);
  transition: border-color 0.3s ease, box-shadow 0.3s ease;
  box-sizing: border-box;
  display: block;
  margin-bottom: 1rem;
}

.input:focus {
  outline: none;
  border-color: #3b82f6; /* blue-500 */
  box-shadow: 0 0 8px 2px rgba(59, 130, 246, 0.4);
}

textarea.input {
  max-width: 350px;  /* same max width as other inputs */
  width: 100%;
  min-height: 5rem;
  resize: vertical;
  box-sizing: border-box;
  display: block;
  margin-bottom: 1rem;
}

/* Labels */
label {
  font-weight: 600;
  font-size: 0.875rem;
  color: #475569;
  margin-bottom: 0.25rem;
  display: block;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

/* Buttons */
.btn {
  font-family: 'Poppins', sans-serif;
  font-weight: 700;
  border: none;
  border-radius: 0.75rem;
  cursor: pointer;
  user-select: none;
  transition: all 0.3s ease;
  min-height: 3rem;
  padding: 0 1.5rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  line-height: 1;
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.08);
  min-width: 120px;           /* Add consistent min-width */
  margin-right: 1rem;         /* Spacing between buttons */
}

.btn-primary {
  background: linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%);
  color: white;
  box-shadow: 0 6px 16px rgba(14, 165, 233, 0.6);
}

.btn-primary:hover,
.btn-primary:focus-visible {
  background: linear-gradient(135deg, #2563eb 0%, #0e7490 100%);
  box-shadow: 0 8px 20px rgba(14, 165, 233, 0.8);
  outline: none;
}

.btn-secondary {
  background: #e0f2fe;
  color: #0369a1;
  box-shadow: 0 3px 8px rgba(3, 105, 161, 0.25);
}

.btn-secondary:hover,
.btn-secondary:focus-visible {
  background: #bae6fd;
  color: #0284c7;
  box-shadow: 0 5px 14px rgba(3, 105, 161, 0.4);
  outline: none;
}

.btn-danger {
  background: #ef4444;
  color: #fff;
  padding: 0.5rem 1.25rem;
  min-width: 2.75rem;
  box-shadow: 0 6px 16px rgba(239, 68, 68, 0.6);
}

.btn-danger:hover,
.btn-danger:focus-visible {
  background: #b91c1c;
  box-shadow: 0 8px 20px rgba(185, 28, 28, 0.8);
  outline: none;
}

/* Total */
.text-right.font-extrabold.text-2xl {
  max-width: 350px;           /* Limit total width */
  margin-left: auto;          /* Align right */
  color: #0f172a;             /* dark blue-gray */
  text-shadow: 0 1px 2px rgba(0,0,0,0.05);
  font-family: 'Poppins', sans-serif;
  margin-top: 2rem;
}

/* Grid spacing tweaks */
.grid > div {
  transition: transform 0.3s ease;
}

.grid > div:hover {
  transform: translateY(-3px);
}

/* Accessibility */
input:invalid,
select:invalid {
  border-color: #ef4444;
  box-shadow: 0 0 6px 2px rgba(239, 68, 68, 0.4);
}

/* Scrollbar for textarea (if overflow) */
textarea.input::-webkit-scrollbar {
  width: 8px;
}

textarea.input::-webkit-scrollbar-thumb {
  background: #3b82f6;
  border-radius: 8px;
}

/* Responsive tweaks */
@media (max-width: 640px) {
  .input {
    max-width: 100%;
    margin-bottom: 1rem;
  }

  .text-right.font-extrabold.text-2xl {
    max-width: 100%;
    margin-left: 0;
    text-align: right;
  }

  .btn {
    min-width: auto;
    width: 100%;
    margin-right: 0;
    margin-bottom: 1rem;
  }
}
</style>
